# Generated by Django 4.2 on 2023-04-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_electionevents_winner_alter_electionevents_parties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionevents',
            name='event_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
